project_id = "edfcezdzxsuduavemdsz"

[api]
enabled = true
port = 54321

[auth]
enabled = true
port = 54324

[edge_functions]
enabled = true
port = 54323

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.send-otp-email]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-staff-notification]
verify_jwt = false

[functions.send-job-card-pdf]
verify_jwt = false

[db]
enabled = true
port = 54322