// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edfcezdzxsuduavemdsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkZmNlemR6eHN1ZHVhdmVtZHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDU5NzIsImV4cCI6MjA2OTQ4MTk3Mn0._hFqGXfSllAHTsxKxGhzinskeRVtZT02Bmnoev9BTTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});